Inicio
    Inteiro: Digito, PotAtual, Binario;
    Real: DigAtual, Decimal;

    Leia(Binario);
    
    Decimal <- 0;
    DigAtual <- 0;
    PotAtual <- 10;
    
    Para Digito de 0 ate 5 faca
    Inicio
        Se Digito = 0 Entao
        Inicio
            PotAtual <- 1;
            Algarismo <- Binario div PotAtual;
            Decimal <- Algarismo * 
        Fim
        Senao
        Inicio
            PotAtual <- PotAtual * 10;
        Fim

        
    Fim
Fim